name: Run Roblox Price Floor Bot

on:
  schedule:
    - cron: '0/15 * * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched (important for commits)

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
          ROBLOX_COOKIE: ${{ secrets.ROBLOX_COOKIE }}
        run: python index.py

      - name: Commit and Push JSON (if changed)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git stash  # Save any unstaged changes
          git pull --rebase  # Update to latest changes
          git stash pop || echo "No stash to apply"  # Restore changes if any

          git add roblox_price_history.json
          git diff --cached --quiet || (git commit -m "Update price floors" && git push)
